# Generated by Django 6.0.1 on 2026-01-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
